### ISSUE TITLE
Setting up a dev corpus makes the train.py script fail

### ISSUE THREAD

**Issue by PonteIneptique** [emanjavacas/pie#5]
When I set up : 

```json
  // path to dev set (same format as input_path)
  "dev_path": "datasets/fro_pos-lemme-morph/dev/dev.tab",
```

Removing the following had no effect

```json
  // proportion of instances in the dev set (ignored if dev_path is passed)
  "dev_split": 0.05,
```

I run into : 

```python traceback
Evaluating model on dev set...

Traceback (most recent call last):
  File "train.py", line 138, in <module>
    trainer.train_epochs(settings.epochs, dev=devset)
  File "/home/thibault/dev/pie/pie/trainer.py", line 254, in train_epochs
    self.train_epoch(dev)
  File "/home/thibault/dev/pie/pie/trainer.py", line 241, in train_epoch
    self.run_check(dev)
  File "/home/thibault/dev/pie/pie/trainer.py", line 193, in run_check
    dev_loss = self.evaluate(dev)
  File "/home/thibault/dev/pie/pie/trainer.py", line 163, in evaluate
    for batch in tqdm.tqdm(dataset, total=total):
UnboundLocalError: local variable 'total' referenced before assignment
```

**Comment by emanjavacas** [comment]
I think this is fixed in dev.
