### ISSUE TITLE
TypeError: run() missing 2 required positional arguments: 'use_beam' and 'beam_width'

### ISSUE THREAD

**Issue by gabays** [emanjavacas/pie#66]
Using a mac (Version 10.13.6), I have just installed _pie_ (`pip install nlp-pie`) in a _virtualenv_ and I need to evaluate two models (one for pos, one for lemma).  When I run ` pie eval`  I get: `TypeError: run() missing 2 required positional arguments: 'use_beam' and 'beam_width'`.

The complete traceback is the following:
```bash
(env) ➜  pie git:(master) ✗ pie eval models/lemma.tar Data_outOfDomain/theatre_original/16_orig/*tsv                                                 [(2.6.2)]
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/pie", line 11, in <module>
    sys.exit(pie_cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pie/scripts/group.py", line 77, in evaluate
    report=report, markdown=markdown)
TypeError: run() missing 2 required positional arguments: 'use_beam' and 'beam_width'
```

For repro:
Models are [available here](https://github.com/e-ditiones/LEM17/tree/master/Models/Train_2/models) and testing data [here](https://github.com/e-ditiones/LEM17/tree/master/Data_outOfDomain).

thanks

**Comment by emanjavacas** [comment]
I believe this should've been fixed already in the last update but last version wasn't uploaded to PyPi. Could you try again?

**Comment by gabays** [comment]
It works! Thx!
